# Values used for the deployed application.
service:
  name: auth-varnish
  certificateAwsArn: "arn:aws:acm:eu-west-1:469211898354:certificate/c9fc4ada-63ee-4951-b1ea-429ba586cbf7"
  external_dns_hostname: upp-prod-publish-eu.upp.ft.com

elb:
  tags: "systemCode=upp,teamDL=universal.publishing.platform@ft.com,environment=p"

s3:
  bucketName: "content-prod-elb-access-logs-eu-west-1"
  prefix: "upp-prod-publish-eu/pub-auth-varnish"
  enabled: "true"
  interval: "5"

encryptedsecrets:
  .htpasswd: "AgB3kyCsgdi++kVMTPLyvlojBrwErlNAM6XGuukcotf3rO5NM/ulp0zuS9Okapbu+UUSfVEZI8RncLoFEy6ifZ63OuwoxeOawo14BHSYgT2kXytZQcxLP/N5a0lBjLejvihWjgvzC0iHpCWiHQXHwN0xG3lhMLQ45BvtwuvMsay3DEPG+lNKvhJxhRDgmTFcy9P/3Dx0gLpBhQWLx2R5gOxE/lDLORwjzwjDaxazp38V9SpE7d/g9Yks3RBakPgLuUqSJlvOI0lznFknw8rcY2xxGd7RLKhdUwSDkpO2OlQd/9BF7KWhUgIjB11wAJ858Gs37D06fYvwXCCX36K8lOeHzSdZ3IG6/X57YNtSbMTXCMSE1397Rl3hAcU1GlLuYaXghynq3JjGi/BrsJDfYS63H4RyrRlhYB8XwZ00Y5CjxxQfixkStY8Bwnvapi+TluPpbj8RwVzsl7zb+pHPzTZcS+CCfDjroaCCp5TOOYezOuFC/em1pQAmJqRuCk5MAVP5RC8j3tKebQbuZtfQgtlFp979x7nlQn52MT25yhz20ZN0PcGP1aLzqdlKtA3qKpRHf1tPCmLWntwX9Sw7oL14IQ6S1L/y/Su5VXILouzksZXUUY2BUY9IHKj2nVdlamfDODFBomYvZjiF2W6rtBohuM1PB+RHRmXMpD/uffyMz5IoK0OD1vBH4NCAxH9S9Emcvss/VCN45H6Skd2I2RKkQblgAu8igJ4T5UxcHlrn/fFFN7S2VS63Sm6Wcx5nJncEgEKEFi5WtSDAiR3ERM51M0NzoqNvnIfARzT9b/KOnQYtx7JrHxnCVeG1UTScDTYu26OHpdrF4fNtFtwXdh9+rmSVPIFrot/lPAaog3E2ul7IHmgQBzkoO2S2LC5S9GXIK9mYZp4pukhKtWQt5ytPccsrHY9SGf2XV0YSOcjTHoIj45r7jqeQVYnEasULbS1OI2OpejE2oqa//h1DSKPDyIKZsS85cSBrKUGNI/EPvXyDoPJUfn5wkMHIrB5Gv9ZglLP/IbfsnY0eC9Qf9WQ5MJNzyfnkHCvt+S+oh8XnV+YIdvlCce7/9eiFfYSRBhqDvPxYMekLILmRL6Yu10cauE5o8982kxPkZNzwFTmLmY4EXbVknsxa7agr3QowXuY9tVKhud+7h485bZiWfNnqv4CX2aG1a5+D+/FR5QhM319/g+9RQtY41KO21s/jre8t7rkQ9HgEwNBl7p2hQiRisDuLg/j3b28e+dNlF0zGRFGxTx57WNxjdkCbmNYzKF65tWvLopngz6xkbbcfzVP9GcBK7vmn4Vo4x+fQEWyv+wDrc8WbIHrdLPwOjnDtGniHcVH5hM7jUtQkbKiFp0txxdFMpQYyLu8bXytAmLUNqpKECxRZdCkCw6nTQ9eIZ+JmvVgUn4EQCm1numvTKW18C8pW7jGEe/+WtdBqUIjtVZfY5qPq+TG0pvuy5BKVBHmjHE2JGYYsUwADJ2urDwdwmBYttNkwC6u6h44qxS+lcmIh1sTFZ1YnwEgvWExVegkTTgTCFgwlRoTJCi6gWRU8CX1B5BDYA1Me0lApLA=="
