# Values used for the deployed application.
service:
  name: auth-varnish
  certificateAwsArn: "arn:aws:acm:us-east-1:469211898354:certificate/58bea0ec-c4c5-4d21-9009-c086e5cac77f"
  external_dns_hostname: upp-staging-publish-us.upp.ft.com

elb:
  tags: "systemCode=upp,teamDL=universal.publishing.platform@ft.com,environment=t"

s3:
  bucketName: "content-prod-elb-access-logs-us-east-1"
  prefix: "upp-staging-publish-us/pub-auth-varnish"
  enabled: "true"
  interval: "5"

encryptedsecrets:
  .htpasswd: "AgAQ/8UY8lAtd3Jy+3b30riG5V3qdzlnMu1JYpUhUCmRAM3CWF2+Y0I0S6PzQWhK15/gwZqn+DaDvaNEQiOEJLVNQk8tAIdiJ4x/SI0EXartkqI3e6fc++JxHk4oBWgOcz+a2RCRb8VI//SV/OgHUQk/7rUHR6OuZOq/6QNohvX6qlB3sOV67MjGe3jpGr0sXPNA8E1HSSq3aR8c9zT9SdzI07fPiSpNzDjHlqpLLNmETXMKuSgPPZRNb9NUqoyjnfVIG/vTmTLY0iVYdI4Z5XsW3+07rLGEfqKxgg4rS+oZ+IMJrsNj/J3Q3fVdwV9JjfCTGhANjbMcgOFjz0rtDNaOU4zmfcmk3wdmJhVs87hYL9+5Mo3ObeMysvZ2GN3wQKUwVugc/wbxiG/sFRixZFV7kr5QKCJj9KMtEn8ymz9vW+HyubxnaU/GdnTLwuLSgmlJotX731LSa1eS7U0agTslH2C0X8hOntbGhgX0ZKCOdFSxrcE+c+WiJzLk5FxikPnVqHbnSDQykU4gNyuK7ASdOpFUvrqu5PgALOth9Sgr+z8tdbrkJZobiTc8o/bWQzJDpF0dRFLw7yJZxgR6NuXzbJgeIbWgaVFcw6nhEL4dMKR4wYjINJvuHtMBg68GNFCXw+akhwHB+lBXFHAFdLgFTBc4idvVAZl6SSTxwJBM7cs/ajjuJmSMzvbVYftmsU1evzSMXZw+3bhZ3Ym2lIYlgBgaqzlcYpTWivgS2oIGHQqaToqlEyAKSl20xUC7PMae0gpNzenYS0pk0JbIM7eMAOmG9bsXa/fZA3oCE14xIz+T4GPBbPjGtE0B7C9fKgihixVBUEoer/dVdAPLMyCMQV1HpwsJYys89cotQPwdSf5CsiboeKfWCeFgScYASz1r2Qe3t6Y/4OfBQfWdgsDj0Q5nRrAf3q/Vh/ZuM53kFC8g1lEUQ5rWyUETP/guq3VnyJIeKP1bPJ6uIeKni1ZbaxbJvKzJZ3E/bVdBozvP3ut6D7zJXE9ub/1IMORx0XjJgm3ZvaEOpBkxwLnBdQ1Aqq9Omk1rC5l/UNVM8xQ8W/64UZo7hX1/quyxYRBKOIChPP9ysHSDfJ5MIOj5258CmBbfZc5PrVN6iF6fWJ0lObqOZnqAgv3kS1Rbqlr24KOjPiVvI3MxdejhokyGhN6IBxZM7nL3gdkmP4TNaZHDlMQ5MU4zy1K3UwNVBIT7N/mZMpjwWSEYGXLiEppBIozNGv1VXpkGfVGHGip3LTRhkensWbJoLjjBKy8H0l3B04NH7MNndqYNqk7fD2LBweTRYMHZsX61lnmHyDUP3CNVr3YBp8PtwNQGOEgiQTaJzZxST/TvITXQxc96XYlDl32u9MNqSPQlg1DC/gpzRUtJ6ocm3Ntzb9JK+mWGc6MHapo9DQ=="
