# Values used for the deployed application.
service:
  name: auth-varnish
  certificateAwsArn: "arn:aws:acm:us-east-1:469211898354:certificate/58bea0ec-c4c5-4d21-9009-c086e5cac77f"
  external_dns_hostname: upp-staging-publish-us.upp.ft.com

elb:
  tags: "systemCode=upp,teamDL=universal.publishing.platform@ft.com,environment=t"

s3:
  bucketName: "content-prod-elb-access-logs-us-east-1"
  prefix: "upp-staging-publish-us/pub-auth-varnish"
  enabled: "true"
  interval: "5"

encryptedsecrets:
  .htpasswd: "AgAnTzI7V2PJBVHqyDE7gAyUY2CqEwbamt23uk9hmUlEffE73yRTa9bvT2mbMqNHoFmVa2mQUZY1N7u+xCFpc9O1hx+1/5cOAWRfMEkTiESdmLe3KeRZHZot10mAjUFguvwbaAphCfsl6bdoCr6tWCcsfokifiSbNc7NT35jC4OOqkilcZydZwJqN9KUsOpsi1DJHvwQy7lzMgchpYpPkzY2HpUwILCTYgx3iBQ/jlrbgSZhBviUzAaFCaEoThCBha4mFAFe+OqfljaQE9zz6uYNitZJTAhbUcDaJtwrltsd+XWMlKajTA7j6y0ItqwUdnMVnl3u01JwabUwkH8OFbR+3DdMKDR6oJnYmdmHXm7bPsCOOzhB/loACKrRMO3L95SsZSGGj1Iiz+EtxaWhEYI+agv+f4iZ6tkV5zJHHX+CQ2v1+TlmQRLvcgTVWEfN5FWZBQaj31GYo/eZAJ1t711UyIkTZKKWz4nzzEk+cEc0f6O2+dIzRC8XcnJLWWefbh1QfL7HatBOtoOaa3pPE4mjUC7IS++P3kxtalh0FA7VG8PLfe8LM1BXP2I/BRSMmDfErcGs8fdx/pr5ZtNXSwFcR8pGCk7pLDe51IELGIqpKBYsz60/QHVhwiSA8dwARiQUR6I+yfXqACX68nJYOmtvuvWTR0+PFeaLeyBhXuai28cAX6N3QsMm6Lut+ven59oTlqqB9m1F2okrxxDkBd+du9ZJXpN4J0HGCoYaCmWd1OppxONnWeZTegyCrfwpge1JiPFcBlxfy6lh2pbaO0Bam3evWGhECbuVpXSI/7TYbW95hb9W9SX7IwJrNN5+FSSC/whC2K7ubhTAvoZceWUyg2UXWNtvcvJWm9E+jQcH7ZZjvIfEuKNlb2mnCvIg2A7ud6lzsmY1vta8u9Ga8dEFVIu+rjD3XwH2HTvazNAYYV2rVCDsfY1hqL7afJ5+cyVbnjGxs1KeFUZmo03ZbF4ASvuZazOwInlBmTKzLBLSaQpAmBrCUN7IeLNMdgOd+hPqTNEqwvDFERKzMjM00gvYc3vEfGLuc33bwbfNtFVBzyaGu/oFQWCg09Tdp1mTjsy4Xa2UxHAhunQ3/nXcflcEnWZ/vlSXgSWOzR6F1yMmcw1lF7pvXIEF9zsNb8NpFz90QnKR26gi4yQjRA0XMcpWYlxAV3i4jcpCt9dAlDE0HA8zMdRreDagJ2ffDTehWmAI8oaO4tTNbrik78CoWyPCX3W2tjjlDiHoZdj/5Rw0JE23m+CcKH4wNZfFrM748Hcx6EwXdtgLGtBSLKPzfvtpBxIdHJ0EIPmy8GvrgwLPbkFRpd5clINFHMfpdAGa"
