# Values used for the deployed application.
service:
  name: auth-varnish
  certificateAwsArn: "arn:aws:acm:eu-west-1:469211898354:certificate/c9fc4ada-63ee-4951-b1ea-429ba586cbf7"
  external_dns_hostname: upp-prod-publish-eu.upp.ft.com

elb:
  tags: "systemCode=upp,teamDL=universal.publishing.platform@ft.com,environment=p"

s3:
  bucketName: "content-prod-elb-access-logs-eu-west-1"
  prefix: "upp-prod-publish-eu/pub-auth-varnish"
  enabled: "true"
  interval: "5"

encryptedsecrets:
  .htpasswd: "AgCzv7iSZfm/rQ9+O+qs7to6KQi4VNyaYnD8/FQ+N7FItVVlM5fwwO9eaJGCEraGzhAGqtHwCtCGHHrpQjAxRaXOSt4g6OxyKe8Qht0IXXzx8MzQ7BNTMlZfcVavlYEyTbc7d2kExlUs+Jxm4ygrfNp2tlZNOGIivZbc7Dui941YhiNcEIY93QZZOfE7kH7AOam34f6hqLlOBezv06OxTAZ4/BtkokzvBc4cv+YwacE0EKK/lsWz4b1NAPKdcpDxskulPgcSwRMYVNfma2iKxhOEAuSZ5SCyTIZBgRiapPihf1XvB72ATaA+OLimJebQqAGYD2FpKLLmMaVnDEFbmK3qcBKNLTpxPMNOkBDNQTaJXuhr9q/llp+oFOoPhT2uppWpka6BaK5D0A21/u/OcdVi45I6lwiJP0hy1/Iw3Bl/g/3AxO4loNJ/ML/2rTFCB9Kbs+ObPaLh5Afc6sIG2mV3PvggqMzLDMB75oum/s7uyiwgZ84LpNY7dmQO2uDw+uxCoQSl1yZp7Zyr36vF4Wn+18uQTVqxGImt3QSCYsimfBuCQNGd76MHxDunfFht8m8+N9MlkMMsT3JfNTW8C241iSSS8WEy4s6zveb3nU+xH/qxyFVRymFLX3Z/agXkqnJ3H21r2hIXynpmRpJAkng9dculIkgdQD/qtaoI5ZA0w9ESPDGLgj/pVqSaDhVlux8CuBdjutwdY4+t5v8Ds06y/yQlMWSdOaOH84Vbwo4e0OuyGG938f0KpKUMBknC4iA8j+nUF1GO4q3F9W+9Ej7lJ1pCcFWuE2H192d0Z+2Lcqlrpl3hHW6kK1w3cp64LmYqwodfq1kBQLdXUdyAvzPYmC0gr+jkKHPnSENllyEGkDuz5G4Qnz5186jWV5gRibEy8dkUG3ruB6Dvud6KImBWfV+uksgGqBHzlPJ6CfK+z3x623FMZD/g3MDV4s9Rjxtl8ItPGZBg8nMh8KWv2uGtJal4SLSFx88A7WBIFa29L8azxide9UTSarPA2bz8+ddppCx3UVA30sBF8yGOaob+MzzBRgGT3sZU/84NxjFAkHV3hsbbuRjnc+cJ8YI+KiRAXcuqLco503Eu7GYzW1Pu1R82XcHkmvzZgzJllSRhYtmQW5zWJHPfmKoPc5pOIgmMB+bjJoML9+MTkHlJ2muvyaUj7Dk1ZLbLUUKqWKXksjlqYemlyscBtJDFXGICx3fPMobDHgjS5pgFBgMvTRlVki3E8No/ZPZx7a/a9tX4U/9epRpp21p6GE0wtV6wDrQR7H87PtjT6YOlMS8ghSXrppGvyvU3KiXFL9249AHLS5nTR41w8qS7Nm+/MDtCgXZnYIIaGJNlhcU/UZ0GIA+q0zq2yEBB1fYT8c+bqKhRFFrqqCptHMmQPkgOQ4rLQXZmlcYFyilkMnJ83rBm8oU9dY1/qjM1qgh7EW++gYOgBvcahzfa27N5mI4frMAVQK9b7a6vRE+ZhyRLHaeMyMWOJvd4D7AHm+CqLIsE2m4="
