# Values used for the deployed application.
service:
  name: auth-varnish
  certificateAwsArn: "arn:aws:acm:us-east-1:469211898354:certificate/58bea0ec-c4c5-4d21-9009-c086e5cac77f"
  external_dns_hostname: upp-prod-publish-us.upp.ft.com

elb:
  tags: "systemCode=upp,teamDL=universal.publishing.platform@ft.com,environment=p"

s3:
  bucketName: "content-prod-elb-access-logs-us-east-1"
  prefix: "upp-prod-publish-us/pub-auth-varnish"
  enabled: "true"
  interval: "5"

encryptedsecrets:
  .htpasswd: "AgB/3px8YP2QUalt4P1BEFCyFAwcdyX/zs/bJ0Uw/CaWft4p5DK6Ci2dzNV7jBsvX+Y30iPQ6FXbSmbpeDAQ8F45wTxzfqrNYWVBNrOKkfr+4/BjP7KOK+fIDQaMw03UU6z3L3Px3CVq4LiRbMjIxLTw3HARUkXt8//7idwLe7vlisA+X1/+eF+nh1OzvoUO2tUVYVEWxERXb1Ww7y9IqZYWxi/mM51kb1wP0fOK3QX1i9xA5Y4zVWYyCXHfextSIVOuwLNqzKglA00fqXi6U9lkh2478vKIlPUKyNCTu+xgOJCC/yQtPbla0VIPfH0hlp08GVXL+nFvBPXhxLfSfBwj6uU0GcXljnoI0xmAmEO0fnh12Tayf7arK2KiomdKcfbwy/ckZjiynZ5gEjV4lHzalMToIxI1rKo24FcvhcztzYE4w7mLU9MeZ7VBw1UkKdhaqKsVM8EcNgXkMfb9A8dIG3q8v/XVaJ1sLlcjURKkBGoOpivWXKrJI8meSsp7ymn3sx6tg5yb7r8KkZR7GhkV+rIKEKSOKrYUL5R+0aU6ROAqApNlx8n8hWh2emXhIIHsFLCcWDz5on8JZlAw2K56x74ce7R/g//tE0rsUjwCpm71jppeG7qutrpPNGvGIS9epg4omM1kycveGWVtInCkuZK9godoXuzMQ3j77nz9xoCl2r3tkKqfoEOnzX/DZPFIilBtNjExJ2kR0aEESNXqnIuSuQcdLF70CQj7Ld1Yxg6OZ9Cy1jHP2NjCLokTMZIZK3HJQVkoCDV5EoDoL97pDvk/H0erkHbntDWmOJ/Q3MI58r7vP6OQebEWkzPlDdpLjaegWk7V71d9fKYSRLDmV9ek5BKUoXR5RkDZKd0jqDxWYzVc7JVZ1LzmdWOJNWy1B2H6UPjiQIPl7J9JXzBR969W0XcW0BFnCgYag/VKT3R42j/8netfDKajl2YGA2ZKFnsl8bVtxYUGxdb3NiN0oB3Bn2LBza0hWiB0rY6CfWqzL2HgI2iLjHi09JIbn68qPQ//k+OJkWBvJQFqQiBPWZsCxuk2JNNwUoxppPPXMVFyJGi6uavrxOygFUn9BZcVgsj9GRoO9WF/LfddkP0kVtuN5tMdG2XwuDlT8urfiazoQG3l1bSa8F1HCbA/2OLDDpoW6zPvr06BekVcDbIVVEUQSV13MknJEu4R4bZhPeeEwcJGnW/fnV6PzdyhhEo5EZn7nJBzlgV0FA0Ve70Foz0tsMsuHTf47oIfUj3ob4+CvrGidw3/zY8V28uf7g/J9ynbHshQhuw8YI8fTShETA1V1Pq3LBs+Dwc3Sd358QvKrtKR7qYZu/PNknoVHApRJjkeOHmQNimVVD/PG3nPmZnSCIXJ8N2AYD4FWepfBqcW71NPpg8I5+wIEizUBUNf6OZ8QjsYsCLIL98wYIL9xTTup+k="
