# Values used for the deployed application.
service:
  name: auth-varnish
  certificateAwsArn: "arn:aws:acm:us-east-1:469211898354:certificate/58bea0ec-c4c5-4d21-9009-c086e5cac77f"
  external_dns_hostname: upp-staging-publish-us.upp.ft.com

elb:
  tags: "systemCode=upp,teamDL=universal.publishing.platform@ft.com,environment=t"

s3:
  bucketName: "content-prod-elb-access-logs-us-east-1"
  prefix: "upp-staging-publish-us/pub-auth-varnish"
  enabled: "true"
  interval: "5"

encryptedsecrets:
  .htpasswd: "AgA+VashZ4Lem1BkJIeTWg5QLgz+sA6O2Mmk03Aoa3ad0Ec+x7V+DELiNkWmw8g4182EPl2SOQ8wtyDJzmOA0pKmo8e54iBOk4D50/ug+SxqoMbc0IdYfX0eAjGVFouPTWHw5+UOTLvglJNIGJl/1LAZasaoDOv3cMBWP7JTFfPRPv/UZXnDEIOOnQFjQduvAgAOrneRJKc2bsHazncgGtdqS0D/rNES7Bz9zvqXud/rKoPYsXz0pwdjRiQLl/ccyZDtpzjmoeKZskx0r6ZDZ+BriPWLqFDdyFaIdlruG6qSaK2TLvlVm4WxLSomdZ0Oz665DiGUSbP72BWSNPf39aXOYsAuehZbbbpNx4J/whH8/K+2B4VdB6CCG9E34aiF44hP7n7QSzXnJ3yUL4J00C93qxqLgdGzAj+pqw5lMizQlfGHiBO/LNL0Lvl+sn+KD1StcMiIsUuCis7NeEFZRbTENfTtzHPjb+HmCzjizPX7MAXV552Kc6+kCDQ377Fh2uSTeSxDakSpuMtuBhurJ8DNL+9auLnDjNjZFkNCqFM4ymoknA27JRxTZk2NbwkCa86KB/LvC0490bOMLQLQBrB7W/sZCISbIR46Llnn5rx7eiCboFjvk9XhlJJICDJoquU9iz7V1eJhBdbh7nVSGY8595wB0r1BHEhaJy7asPkboFFg4T6g3rzD/P6x7RMH55cuDy+3zh657PGMVPI5VwVoS9cH//rUjZbQSYcA9MSvZLgx7sIsldYtxwohVfIE5ReAwkYi9wWGvOqqlq+fMfNuavLfhDQtGHqd5h3TQyrQfHLfmClgOZxzFNVhz1ULMxF4K75OHZ6lMVTV/CT4UBn8DAZ8DFzq0JTzRseJ5ga7WudhzbBAnsUwyLMPg1lWY030dvHH/euYdijxHN0iV4fsIA7zT/WwaCDjIouSuszYU1/Ojzf+v+aj2iWXU//S0d5zB/tzxVYsUujgrB+/Dgt59vQEls+ju+KtowfHZTtxXEvfBBmhzVnNsSvt+OICbkGojSuZ/LTjjCm3w7HCeP3zdE7QIuf94qR374CHG2yHNV58n8pebY7orkF43C0MaeVoBBKcDjFUu1ZoLZmLMnj5qtnylAxdDcuhKNpwBrcLnXIuzddvj/5PAkXTV/B0qCkB6TpJNzp1vl433B64O+fPkow49zhj+TW7aVPE4lzr9rUMUObtoykkka7xkV8Nl1bfnFja7eiuhH8k9OU12on4rG8p4QW7IeS9QiCcY/cDX4/TE7fbn9Tt8feftWECvCBDaryAJEFmY65Hfzk6nsd6wdkAi8vh5sbzG9HanFEAw2rHaMC8XD6PhgkQDnNrMWjKczhW"
