kind: Service
apiVersion: v1
metadata:
  name: {{.Values.service.name}} 
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::027104099916:server-certificate/wildcard.ft.com"
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    app: {{.Values.service.name}}
    visualize: "true" 
spec:
  type: LoadBalancer
  ports: 
    - port: 443
#      name: # The name of this port within the service. Optional if only one port is defined on this service
      targetPort: 80
  selector: 
    app: {{ .Values.service.name }} 
